server:
  port: 8001
  session:
    servlet:
      timeout: 1200
      persistent: true
spring:
  url: jdbc:p6spy:mysql://112.74.44.225:3306/bulleye_admin?characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      username: root
      password: 950602
  mvc:
    throw-exception-if-no-handler-found: true
  flyway:
    baseline-on-migrate: true
  mail:
    host: smtp.exmail.qq.com
    username: chris@zhouhongxing.cn
    port: 25
    password: zZ8302812520
    protocol: smtp
    default-encoding: utf-8
mybatis:
  mapper-locations: classpath*:/mapping/**/*Mapper.xml
  type-aliases-package: com.chris.bulleyeadmin.**.pojo
#basemapper
mapper:
  mappers: com.chris.bulleyeadmin.common.basemapper.BaseMapper
  not-empty: false
  identity: MYSQL
  before: true

defaultSMS: Tencent
aliyunSMS:
  accessKeyId: LTAI1dbEIUJOaeog
  accessKeySecret: 02Rs1BwHg5cQcdbIRrpvhkSXIxC7J2
  signName: U创邦
  product: Dysmsapi
  domain: dysmsapi.aliyuncs.com
tencentSMS:
  appId: 1400047724
  appKey: bc443d70707087066fdf3bc3e203768c
  smsSign : 克里斯周
  product: Dysmsapi
  domain: dysmsapi.aliyuncs.com

serverConfig:
  uploadPath: c:/aaa
  #uploadUrl: http://bulleye.zhouhongxing.cn:8001
  uploadUrl: http://localhost:8001
  isDebug: false
sysconfig:
  organizationId: c77e18b0-1ffa-11e7-b036-00163e0603fa

