server:
  port: 8001
  session:
    servlet:
      timeout: 1200
      persistent: true
spring:
  datasource:
    url: jdbc:p6spy:mysql://127.0.0.1:3306/bulleye_admin?characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      username: root
      password: root
  mvc:
    throw-exception-if-no-handler-found: true
  flyway:
    baseline-on-migrate: true
  mail:
    host: smtp.exmail.qq.com
    username: chris@zhouhongxing.cn
    port: 25
    password: zZ8302812520
    protocol: smtp
    default-encoding: utf-8
mybatis:
  mapper-locations: classpath*:/mapping/**/*Mapper.xml
  type-aliases-package: com.chris.bulleyeadmin.**.pojo
#basemapper
mapper:
  mappers: com.chris.bulleyeadmin.common.basemapper.BaseMapper
  not-empty: false
  identity: MYSQL
  before: true
serverconfig:
  uploadPath: /usr/local/runtime/root/bulleye

