server:
  port: 8001
  session:
    servlet:
      timeout: 1200
      persistent: true
spring:
  datasource:
    url: jdbc:p6spy:mysql://cdb-50qvvhyi.cd.tencentcdb.com:10130/bulleye_admin?characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      username: bullseye
      password: bseadmin
  mvc:
    throw-exception-if-no-handler-found: true
  flyway:
    baseline-on-migrate: true
  mail:
    host: smtp.exmail.qq.com
    username: chris@zhouhongxing.cn
    port: 25
    password: zZ8302812520
    protocol: smtp
    default-encoding: utf-8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  redis:
    host: 118.24.91.197
    password: chris950602
mybatis:
  mapper-locations: classpath*:/mapping/**/*Mapper.xml
  type-aliases-package: com.chris.bulleyeadmin.**.pojo
# minio 参数配置
minio:
  endpoint: http://localhost:60890
  port: 99522
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: bulleye-admin
  domainName:
#basemapper
mapper:
  mappers: com.chris.bulleyeadmin.common.basemapper.BaseMapper
  not-empty: false
  identity: MYSQL
  before: true
defaultSMS: Tencent
aliyunSMS:
  accessKeyId:
  accessKeySecret:
  signName:
  product:
  domain:
tencentSMS:
  appId:
  appKey:
  smsSign :
  product:
  domain: dysmsapi.aliyuncs.com
aliOSSConfig:
  endpoint: oss-cn-chengdu.aliyuncs.com
  accessKeyId:
  accessKeySecret:
  bucketName: bulleye-admin
  domainName:
justauth:
  cache:
  type: default
  qq:
    client-id:
    client-secret:
    redirect-uri: http://oauth.xkcoding.com/demo/oauth/qq/callback
uploadConfig:
  uploadPath: c:/aaa
  #uploadPath: /usr/local/runtime/root/bulleye/upload
  #uploadUrl: http://bulleye.zhouhongxing.cn:8001
  uploadUrl: http://localhost:8008
  prefix: /api/file
  storageType: minio
sysconfig:
  organizationId: c77e18b0-1ffa-11e7-b036-00163e0603fa
encrypKeys:
  rsa:
    privateKey: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAL6RBom7oZ0azYOwftbXchU9j5Kv8/mSemggfERlxPhZLzR0Y4x6yzySzbYLY/mLGGW46yRES/L899lauBNne6hriOJNItbeRODnSqAOYhTqNjqem1ZsppCn83GNx/avjiRH4yoCWmfM/I7QQPTzozmIMxruUQbDHjWAwIWsnOENAgMBAAECgYA67cnhyZ3eYS1wLaHredATdWfyamq9oGgtzu3ekMHqMloAlIU8KbSzVIo8YyVVQ4gV3KsKGfyKdWOHWSBXD8cS8xmgmBJXC8SJOUmNncEv+q/MUG1BFqkQRgywvfGRC7IwKQ5qNQHlTOJ9rQzz77SgKIFKupWp0OBbE0/wmbcrgQJBAOIteGbrzdOsfklgw3rW0FDqBg/TZnQQ3Jrc560QYkpXYG12WX424Tpr8NknfnlgdebJfQEwlH3auVMOhHi/RFECQQDXsYRnrl5H3Z8M8F5KWBYj0qxBdBErQy3pGZXlPEdmaTgTveVdwvADuZaRlLAlnozLGudruDoz9KMDcOz+6k39AkEAhO5gk20H3d7Fom7itTHH4aaJxYdj8ddvMP2glJDKlBLis7MZShsLKQED3z1dEg1lfizx8V8SBx4kSfKAXU9c4QJBAJ7PEBq6kqY9Mcb4D6STWLHFgpiqmZ2N1/bBpNDkYfmwTN6UOZWgWtGTSp4jqNH5+9XrGCsCuK/aVk/JTGWgJA0CQHcU5WfKqh9HzM0VA2RpGbWjtnc+X9cZ6LzrrjwBzXta+MtBVTh32yiR36xDltoEhm2TXizxSrNIHYvDz3VDZTc=
    publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC+kQaJu6GdGs2DsH7W13IVPY+Sr/P5knpoIHxEZcT4WS80dGOMess8ks22C2P5ixhluOskREvy/PfZWrgTZ3uoa4jiTSLW3kTg50qgDmIU6jY6nptWbKaQp/Nxjcf2r44kR+MqAlpnzPyO0ED086M5iDMa7lEGwx41gMCFrJzhDQIDAQAB
  aes: jk@#$IU11233+==


